In [2]:
#Uso basico de Numpy
import sys

In [3]:
import numpy as np

In [4]:
### declarar un array
array_1d=np.array([4.5,3]) 
type(array_1d)

numpy.ndarray

In [5]:
### Dimensiones del array (filas)
array_1d.ndim

1

In [6]:
### forma del array (filas,columnas)
array_1d.shape

(2,)

In [7]:
## Construyendo Matrices "array de un array"
matriz = np.array([[1,2,3],[4,5,6]])
matriz

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
### Dimensiones del array (filas)
matriz.ndim

2

In [9]:
### forma del array (filas,columnas)
matriz.shape

(2, 3)

In [10]:
### matris cero
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
### matris todos 1
np.ones((2))

array([1., 1.])

In [12]:
### matris identidad
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
###matris de numeros aleatorios
np.random.random((2,3))

array([[0.02355737, 0.16312483, 0.37995155],
       [0.51194061, 0.92869087, 0.83981356]])

In [14]:
###leer acrivo de text
!cat np_text.txt

1,2,3
42,2,5
35,65,4
0,1,1


In [15]:
### generar array desde alchivo de texto
np_txt = np.genfromtxt("np_text.txt",delimiter=",")
np_txt

array([[ 1.,  2.,  3.],
       [42.,  2.,  5.],
       [35., 65.,  4.],
       [ 0.,  1.,  1.]])

In [16]:
list_2d=[[list(range(10))],[list(range(10))]]
array_2d =np.array([[list(range(10))],[list(range(10))]])

In [17]:
sys.getsizeof(list_2d)

88

In [18]:
sys.getsizeof(array_2d)

288

In [19]:
big_lista = list(range(1000000))
big_array = np.array(range(1000000))


In [140]:
sys.getsizeof(big_lista)?

In [21]:
sys.getsizeof(big_array)

8000096

In [22]:
%%timeit ### tiempo que talda en hacer un proceso
sum(range(1000000))

29.3 ms ± 4.23 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [23]:
%%timeit
np.sum(np.arange(1000000))

2.78 ms ± 265 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [24]:
np.array([1.,5.4]).dtype

dtype('float64')

In [25]:
np.array([1.,5.4],dtype=int).dtype

dtype('int64')

In [26]:
np.float64

numpy.float64

In [30]:
np.array([1.,2.,"papas"]).dtype

dtype('<U32')

In [40]:
### numpy trabajando con string no es tan eficiente
%%timeit
["{}".format(i) for i in range(100000)]

36.1 ms ± 131 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [33]:
f = np.vectorize(lambda x:"{}".format(x))

In [39]:
%%timeit
f(np.arange(100000))


69.3 ms ± 1.15 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [77]:
###Matrices 2D
matriz_34 =np.array([range(4),range(5,9),range(10,14)])
matriz_34

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

In [79]:
### trabajando con matrices 2D
matriz_34[0]

array([0, 1, 2, 3])

In [80]:
matriz_34[:2]

array([[0, 1, 2, 3],
       [5, 6, 7, 8]])

In [83]:
matriz_34[:,1]

array([ 1,  6, 11])

In [85]:
matriz_34[1,1]

6

In [86]:
### en este caso devolvemos una copia
seleccion = matriz_34[1,3]
print(seleccion)
seleccion=100
matriz_34

8


array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

In [99]:
### en este caso devolvemos una seccion de la matriz la matris *Mucho cuidado con esto*
seccion=matriz_34[:2]
seccion

array([[100,   1,   2,   3],
       [  5,   6,   7,   8]])

In [98]:
seccion[0,0]=100
matriz_34


array([[100,   1,   2,   3],
       [  5,   6,   7,   8],
       [ 10,  11,  12,  13]])

In [103]:
### filter
matriz_32=np.array([[1,4],[2,4],[5,0]])
matriz_32

array([[1, 4],
       [2, 4],
       [5, 0]])

In [107]:
indece_filtrado = matriz_32>=2
indece_filtrado

array([[False,  True],
       [ True,  True],
       [ True, False]])

In [109]:
matriz_32[indece_filtrado]

array([4, 2, 4, 5])

In [113]:
arra1 = np.array([[2,3],
                  [0,1]])
arra2 = np.array([[23,6],
                  [0,42]])

In [115]:
arra1 + arra2

array([[25,  9],
       [ 0, 43]])

In [116]:
arra1 - arra2

array([[-21,  -3],
       [  0, -41]])

In [121]:
### para la  multiplicacion de matrices de usa  @ python>3.5
arra1 @ arra2

array([[ 46, 138],
       [  0,  42]])

In [126]:
###  multiplicacion de matrices python<3.5
arra1.dot(arra2)


array([[ 46, 138],
       [  0,  42]])

In [128]:
a = np.arange(6)                         # 1d array
a

array([0, 1, 2, 3, 4, 5])

In [133]:
b= np.arange(12).reshape(4,3)                         # 2d arra
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [137]:
c= np.arange(24).reshape(2,3,4)                         # 3d arra
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [149]:
#!conda install --prefix {sys.prefix} scipy

import scipy as sc

In [150]:
sc.math.factorial(5)

120